<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Fenestration.Core</RootNamespace>
    <AssemblyName>Fenestration.Core</AssemblyName>
  </PropertyGroup>

</Project>
