using Mark.Licensing;
using Mark.Licensing.Api;
using Microsoft.Data.Sqlite;
using static Mark.LicenceServer.LicenceDatabase;

namespace Mark.LicenceServer;

/// <summary>
/// Licence keys: generated by the admin with a validity (counted from generation), for one company or any company;
/// used once in MARK to extend the account, a product or a feature add-on to the key's date.
/// </summary>
public sealed partial class LicenceService
{
    public const int MaxKeysAtOnce = 100;

    private const string KeyColumns =
        "id, key, company_id, company_name, target, product, feature_id, valid_until_utc, created_utc, state, used_by_company_name, used_utc, note";

    public IReadOnlyList<LicenceKeyInfo> Keys()
    {
        using var connection = Connect();
        using var command = Command(connection, $"SELECT {KeyColumns} FROM licence_keys ORDER BY created_utc DESC, key", null);
        using var reader = command.ExecuteReader();
        var list = new List<LicenceKeyInfo>();
        while (reader.Read()) list.Add(ReadKey(reader));
        return list;
    }

    private LicenceKeyInfo ReadKey(SqliteDataReader r)
    {
        var state = Enum.Parse<KeyState>(r.GetString(9));
        var validUntil = ParseTime(r.GetString(7));
        if (state == KeyState.Unused && validUntil < Now) state = KeyState.Expired;
        return new LicenceKeyInfo(
            Guid.Parse(r.GetString(0)), r.GetString(1),
            r.IsDBNull(2) ? null : Guid.Parse(r.GetString(2)), r.IsDBNull(3) ? null : r.GetString(3),
            Enum.Parse<KeyTarget>(r.GetString(4)), r.IsDBNull(5) ? null : Enum.Parse<Product>(r.GetString(5)),
            r.IsDBNull(6) ? null : r.GetString(6), validUntil, ParseTime(r.GetString(8)), state,
            r.IsDBNull(10) ? null : r.GetString(10), r.IsDBNull(11) ? null : ParseTime(r.GetString(11)), r.IsDBNull(12) ? null : r.GetString(12));
    }

    public IReadOnlyList<LicenceKeyInfo> GenerateKeys(GenerateKeysRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (request.Count is < 1 or > MaxKeysAtOnce) throw ApiException.Invalid($"Generate between 1 and {MaxKeysAtOnce} keys at a time.");
        if (request.ValidUntilUtc <= Now) throw ApiException.Invalid("The keys must be valid until a date in the future.");
        switch (request.Target)
        {
            case KeyTarget.Product when request.Product is null:
                throw ApiException.Invalid("Choose the product (uPVC or Aluminium) the key is for.");
            case KeyTarget.Feature when request.FeatureId is null || !FeatureCatalog.Exists(request.FeatureId):
                throw ApiException.Invalid("Choose the feature the key is for.");
        }

        using var connection = Connect();
        using var transaction = connection.BeginTransaction();
        string? companyName = request.CompanyId is { } companyId ? GetCompany(connection, companyId, transaction).Name : null;
        var ids = new List<Guid>();
        for (int i = 0; i < request.Count; i++)
        {
            var id = Guid.NewGuid();
            ids.Add(id);
            Execute(connection, $"INSERT INTO licence_keys ({KeyColumns}) VALUES ($id, $key, $company, $companyName, $target, $product, $feature, $until, $now, $state, NULL, NULL, $note)",
                transaction,
                ("$id", id.ToString()), ("$key", Secrets.NewLicenceKey()), ("$company", request.CompanyId?.ToString()),
                ("$companyName", companyName), ("$target", request.Target.ToString()),
                ("$product", request.Target == KeyTarget.Product ? request.Product.ToString() : null),
                ("$feature", request.Target == KeyTarget.Feature ? request.FeatureId : null),
                ("$until", Time(request.ValidUntilUtc)), ("$now", Time(Now)), ("$state", KeyState.Unused.ToString()),
                ("$note", string.IsNullOrWhiteSpace(request.Note) ? null : request.Note.Trim()));
        }
        transaction.Commit();
        return Keys().Where(k => ids.Contains(k.Id)).ToList();
    }

    public LicenceKeyInfo RevokeKey(Guid id)
    {
        using var connection = Connect();
        var key = FindKey(connection, "id", id.ToString(), null) ?? throw ApiException.NotFound("The key");
        if (key.State == KeyState.Used) throw ApiException.Conflict("The key has already been used; change the account instead.");
        Execute(connection, "UPDATE licence_keys SET state = $state WHERE id = $id", null,
            ("$state", KeyState.Revoked.ToString()), ("$id", id.ToString()));
        return FindKey(connection, "id", id.ToString(), null)!;
    }

    private LicenceKeyInfo? FindKey(SqliteConnection connection, string column, string value, SqliteTransaction? transaction)
    {
        using var command = Command(connection, $"SELECT {KeyColumns} FROM licence_keys WHERE {column} = $value", transaction, ("$value", value));
        using var reader = command.ExecuteReader();
        return reader.Read() ? ReadKey(reader) : null;
    }

    /// <summary>Applies an unused key to a company (never shortens anything). Returns the updated company and a message.</summary>
    private (CompanyRow Company, string Message) ApplyKey(SqliteConnection connection, CompanyRow company, string keyText, SqliteTransaction transaction)
    {
        var key = FindKey(connection, "key", Secrets.NormaliseKey(keyText), transaction);
        ApiException Refused(string message) => new(400, ErrorCodes.KeyInvalid, message);
        if (key is null) throw Refused("This licence key is not valid. Check that it was typed correctly.");
        switch (key.State)
        {
            case KeyState.Used: throw Refused("This licence key has already been used.");
            case KeyState.Revoked: throw Refused("This licence key has been cancelled.");
            case KeyState.Expired: throw Refused("This licence key has expired.");
        }
        if (key.CompanyId is { } forCompany && forCompany != company.Id)
            throw Refused("This licence key is for another company.");

        static DateTime Later(DateTime a, DateTime b) => a > b ? a : b;
        string until = LicenceDates.Format(key.ValidUntilUtc);
        string message;
        switch (key.Target)
        {
            case KeyTarget.Account:
                company = company with { ValidUntilUtc = Later(company.ValidUntilUtc, key.ValidUntilUtc) };
                message = $"Your MARK licence is now valid until {LicenceDates.Format(company.ValidUntilUtc)}.";
                break;
            case KeyTarget.Product:
            {
                var product = key.Product!.Value;
                var products = company.Products.ToList();
                int index = products.FindIndex(p => p.Product == product);
                if (index < 0) products.Add(new ProductLicence(product, key.ValidUntilUtc));
                else products[index] = products[index] with { ValidUntilUtc = Later(products[index].ValidUntilUtc, key.ValidUntilUtc) };
                company = company with { Products = products };
                message = $"{product.DisplayName()} is now valid until {LicenceDates.Format(products.First(p => p.Product == product).ValidUntilUtc)}.";
                break;
            }
            default:
            {
                string featureId = key.FeatureId!;
                var addOns = company.AddOns.ToList();
                int index = addOns.FindIndex(a => a.FeatureId == featureId);
                if (index < 0) addOns.Add(new AddOn(featureId, key.ValidUntilUtc));
                else addOns[index] = addOns[index] with { ValidUntilUtc = Later(addOns[index].ValidUntilUtc, key.ValidUntilUtc) };
                company = company with { AddOns = addOns, RemovedFeatures = company.RemovedFeatures.Where(f => f != featureId).ToList() };
                message = $"{FeatureCatalog.NameOf(featureId)} has been added until {until}.";
                break;
            }
        }

        WriteCompany(connection, company, transaction, insert: false);
        Execute(connection, "UPDATE licence_keys SET state = $state, used_by_company_name = $company, used_utc = $now WHERE id = $id", transaction,
            ("$state", KeyState.Used.ToString()), ("$company", company.Name), ("$now", Time(Now)), ("$id", key.Id.ToString()));
        return (company, message);
    }
}
