<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Fenestration.Designer</RootNamespace>
    <AssemblyName>Fenestration.Designer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fenestration.Core\Fenestration.Core.csproj" />
  </ItemGroup>

</Project>
